run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.25.3"

linters:
  enable:
    # Performance
    - bodyclose
    - errcheck
    - errorlint
    - exportloopref
    - gocritic
    - gocyclo
    - ineffassign
    - misspell
    - prealloc
    - unused
    - wastedassign

    # Style
    - gofmt
    - goimports
    - gosimple
    - govet
    - vet

    # Code quality
    - copyloopvar
    - durationcheck
    - forbidigo
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unparam
    - usestdlibvars

    # Security
    - gosec
    - sqlc

linters-settings:
  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - assignOp
      - badCond
      - boolExprSimplify
      - builtinShadow
      - commentedOutCode
      - defaultCaseOrder
      - deferInLoop
      - deferUnlambda
      - docStubsChecker
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - evalOrder
      - exitAfterDefer
      - externalPackageExec
      - filepathJoin
      - flagDeref
      - flagName
      - floatCompare
      - forcetypeassert
      - foreachExinterfaceRange
      - ifElseChain
      - importShadow
      - ineffectiveAppend
      - initClause
      - intRange
      - invalidPrintfUseCase
      - isEmptyFunc
      - licenseHeader
      - logicalKeywordOrder
      - makezero
      - methodExprCall
      - missedUnderscoreField
      - missingEnumTypes
      - missingLoggerField
      - mixedNamedParams
      - modifyResourceInEffectiveCall
      - namedReturnUseCase
      - nestingLevel
      - nilValReturn
      - noExec
      - octalLiteral
      - offByOne
      - paramTypeCombine
      - preferFilepathJoin
      - preferStringWriter
      - ptrToRefParam
      - rangeExprCopy
      - rangeValCopy
      - redundantCond
      - redundantFlag
      - redundantSprint
      - regexpMust
      - regexpPattern
      - regexpSimplify
      - returnAfterLog
      - ruleguard
      - simplifyTypeConversion
      - sliceDereference
    disabled-checks:
      - hugeParam
      - whyNoLinter

  gosec:
    excludes:
      # G101: Potential hardcoded credentials - we don't have any
      - G101

  stylecheck:
    checks:
      - all
      - -ST1000
      - -ST1003
      - -ST1016
      - -ST1020
      - -ST1021
      - -ST1022

  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - bodyclose
        - depguard
        - dupl
        - funlen
        - gochecknoglobals
        - gochecknoinits
        - gocyclo
        - gosec
        - lll
        - unparam
        - varnamelen
        - wrapcheck

    # Ignore long lines in code
    - linters:
        - lll
      source: "^//|^\\s*//|test|Test"

  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-case-sensitive: false
