version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.25.3"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    # Performance
    - bodyclose
    - errcheck
    - errorlint
    - gocritic
    - gocyclo
    - ineffassign
    - misspell
    - prealloc
    - unused

    # Style
    - govet

    # Code quality
    - copyloopvar
    - durationcheck
    - forbidigo
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - staticcheck
    - unparam
    - usestdlibvars

    # Security
    - gosec

  settings:
    gocyclo:
      min-complexity: 15

    gocritic:
      enabled-checks:
        - boolExprSimplify
        - builtinShadow
        - commentedOutCode
        - deferInLoop
        - deferUnlambda
        - emptyFallthrough
        - emptyStringTest
        - evalOrder
        - filepathJoin
        - importShadow
        - initClause
        - methodExprCall
        - nestingReduce
        - nilValReturn
        - octalLiteral
        - paramTypeCombine
        - ptrToRefParam
        - rangeExprCopy
        - rangeValCopy
        - regexpPattern
        - regexpSimplify
        - sloppyReassign
        - stringXbytes
        - typeAssertChain
        - typeUnparen
        - unlabelStmt
        - unnamedResult
        - unnecessaryBlock
        - unnecessaryDefer
        - weakCond
        - yodaStyleExpr

    gosec:
      excludes:
        - G101

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022

    errcheck:
      check-type-assertions: false
      check-blank: false

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - bodyclose
          - dupl
          - funlen
          - gocyclo
          - gosec
          - lll
          - unparam

      - linters:
          - lll
        source: "^//|^\\s*//|test|Test"
